'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/Mail/FDA_MAIL.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_WS_MAIL_FDA_MAIL() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_WS_MAIL_FDA_MAIL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.104/ws_authen2/AUTHENTICATION.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_WS_AUTHEN_Authentication() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_WS_AUTHEN_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.104/WS_AUTHEN3/AUTHENTICATION.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_WS_AUTHEN3_Authentication() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_WS_AUTHEN3_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/WS_DATE/Service1.svc")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_WS_GETDATE_WORKING_Service1() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_WS_GETDATE_WORKING_Service1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/WS_TaxnoAuthorize_BSN/WS_TaxnoAuthorize_BSN.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_WS_TaxnoAuthorize_BSN_WebService1() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_WS_TaxnoAuthorize_BSN_WebService1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/WS_get_Profile_By_Identify/WS_Taxno_TaxnoAuthorize.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_WS_Taxno_TaxnoAuthorize_2_WebService1() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_WS_Taxno_TaxnoAuthorize_2_WebService1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.133/SPECIAL_PAYMENT_TXC_BSN/WEBSERVICE/SV_CHECK_PAYMENT.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_SV_CHECK_PAYMENT_SV_CHECK_PAYMENT() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_SV_CHECK_PAYMENT_SV_CHECK_PAYMENT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.105/WS_ERROR_CENTER/WEB_SERVICE/WS_ERROR_CENTER.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_WS_ERROR_CENTER_WS_ERROR_CENTER() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_WS_ERROR_CENTER_WS_ERROR_CENTER"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.111.28.134;Initial Catalog=FDA_MDC_DEMO;User ID=fusion;Password=P@"& _ 
            "ssw0rd")>  _
        Public ReadOnly Property FDA_MDC_DEMOConnectionString() As String
            Get
                Return CType(Me("FDA_MDC_DEMOConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.111.28.134;Initial Catalog=FDA_MDC_DEMO;User ID=fusion;Password=P@"& _ 
            "ssw0rd")>  _
        Public ReadOnly Property FDA_MDC_DEMOConnectionString1() As String
            Get
                Return CType(Me("FDA_MDC_DEMOConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/WS_SMS/FDA_SMS.asmx")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_FDA_SMS_FDA_SMS() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_FDA_SMS_FDA_SMS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://164.115.28.108/WS_DATE/Service1.svc")>  _
        Public ReadOnly Property FDA_CERTIFICATE_MDC_STOP_SAT_SUN_Service1() As String
            Get
                Return CType(Me("FDA_CERTIFICATE_MDC_STOP_SAT_SUN_Service1"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.FDA_CERTIFICATE_MDC.My.MySettings
            Get
                Return Global.FDA_CERTIFICATE_MDC.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
