'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="LGT_FOOD_NEW")>  _
Partial Public Class Linq_FoodDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Insertfalcn(instance As falcn)
    End Sub
  Partial Private Sub Updatefalcn(instance As falcn)
    End Sub
  Partial Private Sub Deletefalcn(instance As falcn)
    End Sub
  Partial Private Sub Insertfabsncdtlcn(instance As fabsncdtlcn)
    End Sub
  Partial Private Sub Updatefabsncdtlcn(instance As fabsncdtlcn)
    End Sub
  Partial Private Sub Deletefabsncdtlcn(instance As fabsncdtlcn)
    End Sub
  Partial Private Sub Insertfalcnaddr(instance As falcnaddr)
    End Sub
  Partial Private Sub Updatefalcnaddr(instance As falcnaddr)
    End Sub
  Partial Private Sub Deletefalcnaddr(instance As falcnaddr)
    End Sub
  Partial Private Sub Insertflabelinitial(instance As flabelinitial)
    End Sub
  Partial Private Sub Updateflabelinitial(instance As flabelinitial)
    End Sub
  Partial Private Sub Deleteflabelinitial(instance As flabelinitial)
    End Sub
  Partial Private Sub Insertfafdtype(instance As fafdtype)
    End Sub
  Partial Private Sub Updatefafdtype(instance As fafdtype)
    End Sub
  Partial Private Sub Deletefafdtype(instance As fafdtype)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("LGT_FOOD_DEMO2ConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property falcns() As System.Data.Linq.Table(Of falcn)
		Get
			Return Me.GetTable(Of falcn)
		End Get
	End Property
	
	Public ReadOnly Property fabsncdtlcns() As System.Data.Linq.Table(Of fabsncdtlcn)
		Get
			Return Me.GetTable(Of fabsncdtlcn)
		End Get
	End Property
	
	Public ReadOnly Property falcnaddrs() As System.Data.Linq.Table(Of falcnaddr)
		Get
			Return Me.GetTable(Of falcnaddr)
		End Get
	End Property
	
	Public ReadOnly Property flabelinitials() As System.Data.Linq.Table(Of flabelinitial)
		Get
			Return Me.GetTable(Of flabelinitial)
		End Get
	End Property
	
	Public ReadOnly Property fafdtypes() As System.Data.Linq.Table(Of fafdtype)
		Get
			Return Me.GetTable(Of fafdtype)
		End Get
	End Property
	
	Public ReadOnly Property falcntypes() As System.Data.Linq.Table(Of falcntype)
		Get
			Return Me.GetTable(Of falcntype)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.falcn")>  _
Partial Public Class falcn
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _pvncd As System.Nullable(Of Short)
	
	Private _lcntypecd As System.Nullable(Of Short)
	
	Private _lcnno As System.Nullable(Of Integer)
	
	Private _lcnabbr As String
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _lcnscd As System.Nullable(Of Integer)
	
	Private _lctnmcd1 As System.Nullable(Of Integer)
	
	Private _lctnmcd2 As System.Nullable(Of Integer)
	
	Private _lctcd As System.Nullable(Of Integer)
	
	Private _bsncd1 As System.Nullable(Of Integer)
	
	Private _bsncd2 As System.Nullable(Of Integer)
	
	Private _bsncd3 As System.Nullable(Of Integer)
	
	Private _cdtst As System.Nullable(Of Integer)
	
	Private _machine As String
	
	Private _laber As String
	
	Private _remark As String
	
	Private _appvdate As System.Nullable(Of Date)
	
	Private _expdate As System.Nullable(Of Date)
	
	Private _lctlcnno As String
	
	Private _extappvdate As System.Nullable(Of Date)
	
	Private _factstcd As System.Nullable(Of Char)
	
	Private _lcnst As System.Nullable(Of Char)
	
	Private _lcnappvtp As System.Nullable(Of Char)
	
	Private _rcptpayst As System.Nullable(Of Short)
	
	Private _cncstfcd As System.Nullable(Of Integer)
	
	Private _cnccd As System.Nullable(Of Short)
	
	Private _cncrcvdate As System.Nullable(Of Date)
	
	Private _cncdate As System.Nullable(Of Date)
	
	Private _causecd As System.Nullable(Of Short)
	
	Private _document As String
	
	Private _amphrcd As System.Nullable(Of Short)
	
	Private _chngwtcd As System.Nullable(Of Short)
	
	Private _lstfcd As System.Nullable(Of Integer)
	
	Private _lmdfdate As System.Nullable(Of Date)
	
	Private _reflcnst As System.Nullable(Of Char)
	
	Private _refappvtp As System.Nullable(Of Char)
	
	Private _reflcnpvncd As System.Nullable(Of Short)
	
	Private _reflcnno As System.Nullable(Of Integer)
	
	Private _refchngwtcd As System.Nullable(Of Short)
	
	Private _rcvno As System.Nullable(Of Integer)
	
	Private _rcvdate As System.Nullable(Of Date)
	
	Private _cnsdcd As System.Nullable(Of Integer)
	
	Private _xmlnm As String
	
	Private _TRANSECTION_ID_UPLOAD As System.Nullable(Of Integer)
	
	Private _CITIZEN_ID As String
	
	Private _CITIZEN_ID_UPLOAD As String
	
	Private _CITIZEN_ID_AUTHORIZE As String
	
	Private _CUS_EXPLAIN As String
	
	Private _STAFF_EXPLAIN As String
	
	Private _PAYMENT_REPAIR As System.Nullable(Of Integer)
	
	Private _CB_TYPE As System.Nullable(Of Integer)
	
	Private _CB_CODE As String
	
	Private _CB_ID_AUTHORIZE As String
	
	Private _AUDIT_TR_ID As System.Nullable(Of Integer)
	
	Private _AUDIT_XMLNAME As String
	
	Private _AUDIT_UPLOAD_CITIZEN As String
	
	Private _AUDIT_UPLOAD_DATE As String
	
	Private _MONITOR_TR_ID As System.Nullable(Of Integer)
	
	Private _MONITOR_XMLNAME As String
	
	Private _MONITOR_UPLOAD_CITIZEN As String
	
	Private _MONITOR_UPLOAD_DATE As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlcntypecdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlcntypecdChanged()
    End Sub
    Partial Private Sub OnlcnnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnnoChanged()
    End Sub
    Partial Private Sub OnlcnabbrChanging(value As String)
    End Sub
    Partial Private Sub OnlcnabbrChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnlcnscdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnscdChanged()
    End Sub
    Partial Private Sub Onlctnmcd1Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onlctnmcd1Changed()
    End Sub
    Partial Private Sub Onlctnmcd2Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onlctnmcd2Changed()
    End Sub
    Partial Private Sub OnlctcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctcdChanged()
    End Sub
    Partial Private Sub Onbsncd1Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onbsncd1Changed()
    End Sub
    Partial Private Sub Onbsncd2Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onbsncd2Changed()
    End Sub
    Partial Private Sub Onbsncd3Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onbsncd3Changed()
    End Sub
    Partial Private Sub OncdtstChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncdtstChanged()
    End Sub
    Partial Private Sub OnmachineChanging(value As String)
    End Sub
    Partial Private Sub OnmachineChanged()
    End Sub
    Partial Private Sub OnlaberChanging(value As String)
    End Sub
    Partial Private Sub OnlaberChanged()
    End Sub
    Partial Private Sub OnremarkChanging(value As String)
    End Sub
    Partial Private Sub OnremarkChanged()
    End Sub
    Partial Private Sub OnappvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnappvdateChanged()
    End Sub
    Partial Private Sub OnexpdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnexpdateChanged()
    End Sub
    Partial Private Sub OnlctlcnnoChanging(value As String)
    End Sub
    Partial Private Sub OnlctlcnnoChanged()
    End Sub
    Partial Private Sub OnextappvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnextappvdateChanged()
    End Sub
    Partial Private Sub OnfactstcdChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnfactstcdChanged()
    End Sub
    Partial Private Sub OnlcnstChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnlcnstChanged()
    End Sub
    Partial Private Sub OnlcnappvtpChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnlcnappvtpChanged()
    End Sub
    Partial Private Sub OnrcptpaystChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnrcptpaystChanged()
    End Sub
    Partial Private Sub OncncstfcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncncstfcdChanged()
    End Sub
    Partial Private Sub OncnccdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OncnccdChanged()
    End Sub
    Partial Private Sub OncncrcvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OncncrcvdateChanged()
    End Sub
    Partial Private Sub OncncdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OncncdateChanged()
    End Sub
    Partial Private Sub OncausecdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OncausecdChanged()
    End Sub
    Partial Private Sub OndocumentChanging(value As String)
    End Sub
    Partial Private Sub OndocumentChanged()
    End Sub
    Partial Private Sub OnamphrcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnamphrcdChanged()
    End Sub
    Partial Private Sub OnchngwtcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnchngwtcdChanged()
    End Sub
    Partial Private Sub OnlstfcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlstfcdChanged()
    End Sub
    Partial Private Sub OnlmdfdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnlmdfdateChanged()
    End Sub
    Partial Private Sub OnreflcnstChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnreflcnstChanged()
    End Sub
    Partial Private Sub OnrefappvtpChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnrefappvtpChanged()
    End Sub
    Partial Private Sub OnreflcnpvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnreflcnpvncdChanged()
    End Sub
    Partial Private Sub OnreflcnnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnreflcnnoChanged()
    End Sub
    Partial Private Sub OnrefchngwtcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnrefchngwtcdChanged()
    End Sub
    Partial Private Sub OnrcvnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnrcvnoChanged()
    End Sub
    Partial Private Sub OnrcvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnrcvdateChanged()
    End Sub
    Partial Private Sub OncnsdcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncnsdcdChanged()
    End Sub
    Partial Private Sub OnxmlnmChanging(value As String)
    End Sub
    Partial Private Sub OnxmlnmChanged()
    End Sub
    Partial Private Sub OnTRANSECTION_ID_UPLOADChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTRANSECTION_ID_UPLOADChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnCITIZEN_ID_UPLOADChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_ID_UPLOADChanged()
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnCUS_EXPLAINChanging(value As String)
    End Sub
    Partial Private Sub OnCUS_EXPLAINChanged()
    End Sub
    Partial Private Sub OnSTAFF_EXPLAINChanging(value As String)
    End Sub
    Partial Private Sub OnSTAFF_EXPLAINChanged()
    End Sub
    Partial Private Sub OnPAYMENT_REPAIRChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPAYMENT_REPAIRChanged()
    End Sub
    Partial Private Sub OnCB_TYPEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCB_TYPEChanged()
    End Sub
    Partial Private Sub OnCB_CODEChanging(value As String)
    End Sub
    Partial Private Sub OnCB_CODEChanged()
    End Sub
    Partial Private Sub OnCB_ID_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCB_ID_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnAUDIT_TR_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnAUDIT_TR_IDChanged()
    End Sub
    Partial Private Sub OnAUDIT_XMLNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnAUDIT_XMLNAMEChanged()
    End Sub
    Partial Private Sub OnAUDIT_UPLOAD_CITIZENChanging(value As String)
    End Sub
    Partial Private Sub OnAUDIT_UPLOAD_CITIZENChanged()
    End Sub
    Partial Private Sub OnAUDIT_UPLOAD_DATEChanging(value As String)
    End Sub
    Partial Private Sub OnAUDIT_UPLOAD_DATEChanged()
    End Sub
    Partial Private Sub OnMONITOR_TR_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMONITOR_TR_IDChanged()
    End Sub
    Partial Private Sub OnMONITOR_XMLNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnMONITOR_XMLNAMEChanged()
    End Sub
    Partial Private Sub OnMONITOR_UPLOAD_CITIZENChanging(value As String)
    End Sub
    Partial Private Sub OnMONITOR_UPLOAD_CITIZENChanged()
    End Sub
    Partial Private Sub OnMONITOR_UPLOAD_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMONITOR_UPLOAD_DATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="SmallInt")>  _
	Public Property pvncd() As System.Nullable(Of Short)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypecd", DbType:="SmallInt")>  _
	Public Property lcntypecd() As System.Nullable(Of Short)
		Get
			Return Me._lcntypecd
		End Get
		Set
			If (Me._lcntypecd.Equals(value) = false) Then
				Me.OnlcntypecdChanging(value)
				Me.SendPropertyChanging
				Me._lcntypecd = value
				Me.SendPropertyChanged("lcntypecd")
				Me.OnlcntypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnno", DbType:="Int")>  _
	Public Property lcnno() As System.Nullable(Of Integer)
		Get
			Return Me._lcnno
		End Get
		Set
			If (Me._lcnno.Equals(value) = false) Then
				Me.OnlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lcnno = value
				Me.SendPropertyChanged("lcnno")
				Me.OnlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnabbr", DbType:="Char(3)")>  _
	Public Property lcnabbr() As String
		Get
			Return Me._lcnabbr
		End Get
		Set
			If (String.Equals(Me._lcnabbr, value) = false) Then
				Me.OnlcnabbrChanging(value)
				Me.SendPropertyChanging
				Me._lcnabbr = value
				Me.SendPropertyChanged("lcnabbr")
				Me.OnlcnabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnscd", DbType:="Int")>  _
	Public Property lcnscd() As System.Nullable(Of Integer)
		Get
			Return Me._lcnscd
		End Get
		Set
			If (Me._lcnscd.Equals(value) = false) Then
				Me.OnlcnscdChanging(value)
				Me.SendPropertyChanging
				Me._lcnscd = value
				Me.SendPropertyChanged("lcnscd")
				Me.OnlcnscdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmcd1", DbType:="Int")>  _
	Public Property lctnmcd1() As System.Nullable(Of Integer)
		Get
			Return Me._lctnmcd1
		End Get
		Set
			If (Me._lctnmcd1.Equals(value) = false) Then
				Me.Onlctnmcd1Changing(value)
				Me.SendPropertyChanging
				Me._lctnmcd1 = value
				Me.SendPropertyChanged("lctnmcd1")
				Me.Onlctnmcd1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmcd2", DbType:="Int")>  _
	Public Property lctnmcd2() As System.Nullable(Of Integer)
		Get
			Return Me._lctnmcd2
		End Get
		Set
			If (Me._lctnmcd2.Equals(value) = false) Then
				Me.Onlctnmcd2Changing(value)
				Me.SendPropertyChanging
				Me._lctnmcd2 = value
				Me.SendPropertyChanged("lctnmcd2")
				Me.Onlctnmcd2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctcd", DbType:="Int")>  _
	Public Property lctcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctcd
		End Get
		Set
			If (Me._lctcd.Equals(value) = false) Then
				Me.OnlctcdChanging(value)
				Me.SendPropertyChanging
				Me._lctcd = value
				Me.SendPropertyChanged("lctcd")
				Me.OnlctcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_bsncd1", DbType:="Int")>  _
	Public Property bsncd1() As System.Nullable(Of Integer)
		Get
			Return Me._bsncd1
		End Get
		Set
			If (Me._bsncd1.Equals(value) = false) Then
				Me.Onbsncd1Changing(value)
				Me.SendPropertyChanging
				Me._bsncd1 = value
				Me.SendPropertyChanged("bsncd1")
				Me.Onbsncd1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_bsncd2", DbType:="Int")>  _
	Public Property bsncd2() As System.Nullable(Of Integer)
		Get
			Return Me._bsncd2
		End Get
		Set
			If (Me._bsncd2.Equals(value) = false) Then
				Me.Onbsncd2Changing(value)
				Me.SendPropertyChanging
				Me._bsncd2 = value
				Me.SendPropertyChanged("bsncd2")
				Me.Onbsncd2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_bsncd3", DbType:="Int")>  _
	Public Property bsncd3() As System.Nullable(Of Integer)
		Get
			Return Me._bsncd3
		End Get
		Set
			If (Me._bsncd3.Equals(value) = false) Then
				Me.Onbsncd3Changing(value)
				Me.SendPropertyChanging
				Me._bsncd3 = value
				Me.SendPropertyChanged("bsncd3")
				Me.Onbsncd3Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cdtst", DbType:="Int")>  _
	Public Property cdtst() As System.Nullable(Of Integer)
		Get
			Return Me._cdtst
		End Get
		Set
			If (Me._cdtst.Equals(value) = false) Then
				Me.OncdtstChanging(value)
				Me.SendPropertyChanging
				Me._cdtst = value
				Me.SendPropertyChanged("cdtst")
				Me.OncdtstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_machine", DbType:="NVarChar(MAX)")>  _
	Public Property machine() As String
		Get
			Return Me._machine
		End Get
		Set
			If (String.Equals(Me._machine, value) = false) Then
				Me.OnmachineChanging(value)
				Me.SendPropertyChanging
				Me._machine = value
				Me.SendPropertyChanged("machine")
				Me.OnmachineChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_laber", DbType:="NVarChar(MAX)")>  _
	Public Property laber() As String
		Get
			Return Me._laber
		End Get
		Set
			If (String.Equals(Me._laber, value) = false) Then
				Me.OnlaberChanging(value)
				Me.SendPropertyChanging
				Me._laber = value
				Me.SendPropertyChanged("laber")
				Me.OnlaberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_remark", DbType:="NVarChar(MAX)")>  _
	Public Property remark() As String
		Get
			Return Me._remark
		End Get
		Set
			If (String.Equals(Me._remark, value) = false) Then
				Me.OnremarkChanging(value)
				Me.SendPropertyChanging
				Me._remark = value
				Me.SendPropertyChanged("remark")
				Me.OnremarkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appvdate", DbType:="Date")>  _
	Public Property appvdate() As System.Nullable(Of Date)
		Get
			Return Me._appvdate
		End Get
		Set
			If (Me._appvdate.Equals(value) = false) Then
				Me.OnappvdateChanging(value)
				Me.SendPropertyChanging
				Me._appvdate = value
				Me.SendPropertyChanged("appvdate")
				Me.OnappvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate", DbType:="Date")>  _
	Public Property expdate() As System.Nullable(Of Date)
		Get
			Return Me._expdate
		End Get
		Set
			If (Me._expdate.Equals(value) = false) Then
				Me.OnexpdateChanging(value)
				Me.SendPropertyChanging
				Me._expdate = value
				Me.SendPropertyChanged("expdate")
				Me.OnexpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctlcnno", DbType:="VarChar(8)")>  _
	Public Property lctlcnno() As String
		Get
			Return Me._lctlcnno
		End Get
		Set
			If (String.Equals(Me._lctlcnno, value) = false) Then
				Me.OnlctlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lctlcnno = value
				Me.SendPropertyChanged("lctlcnno")
				Me.OnlctlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_extappvdate", DbType:="Date")>  _
	Public Property extappvdate() As System.Nullable(Of Date)
		Get
			Return Me._extappvdate
		End Get
		Set
			If (Me._extappvdate.Equals(value) = false) Then
				Me.OnextappvdateChanging(value)
				Me.SendPropertyChanging
				Me._extappvdate = value
				Me.SendPropertyChanged("extappvdate")
				Me.OnextappvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_factstcd", DbType:="Char(1)")>  _
	Public Property factstcd() As System.Nullable(Of Char)
		Get
			Return Me._factstcd
		End Get
		Set
			If (Me._factstcd.Equals(value) = false) Then
				Me.OnfactstcdChanging(value)
				Me.SendPropertyChanging
				Me._factstcd = value
				Me.SendPropertyChanged("factstcd")
				Me.OnfactstcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnst", DbType:="Char(1)")>  _
	Public Property lcnst() As System.Nullable(Of Char)
		Get
			Return Me._lcnst
		End Get
		Set
			If (Me._lcnst.Equals(value) = false) Then
				Me.OnlcnstChanging(value)
				Me.SendPropertyChanging
				Me._lcnst = value
				Me.SendPropertyChanged("lcnst")
				Me.OnlcnstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnappvtp", DbType:="Char(1)")>  _
	Public Property lcnappvtp() As System.Nullable(Of Char)
		Get
			Return Me._lcnappvtp
		End Get
		Set
			If (Me._lcnappvtp.Equals(value) = false) Then
				Me.OnlcnappvtpChanging(value)
				Me.SendPropertyChanging
				Me._lcnappvtp = value
				Me.SendPropertyChanged("lcnappvtp")
				Me.OnlcnappvtpChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcptpayst", DbType:="SmallInt")>  _
	Public Property rcptpayst() As System.Nullable(Of Short)
		Get
			Return Me._rcptpayst
		End Get
		Set
			If (Me._rcptpayst.Equals(value) = false) Then
				Me.OnrcptpaystChanging(value)
				Me.SendPropertyChanging
				Me._rcptpayst = value
				Me.SendPropertyChanged("rcptpayst")
				Me.OnrcptpaystChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cncstfcd", DbType:="Int")>  _
	Public Property cncstfcd() As System.Nullable(Of Integer)
		Get
			Return Me._cncstfcd
		End Get
		Set
			If (Me._cncstfcd.Equals(value) = false) Then
				Me.OncncstfcdChanging(value)
				Me.SendPropertyChanging
				Me._cncstfcd = value
				Me.SendPropertyChanged("cncstfcd")
				Me.OncncstfcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cnccd", DbType:="SmallInt")>  _
	Public Property cnccd() As System.Nullable(Of Short)
		Get
			Return Me._cnccd
		End Get
		Set
			If (Me._cnccd.Equals(value) = false) Then
				Me.OncnccdChanging(value)
				Me.SendPropertyChanging
				Me._cnccd = value
				Me.SendPropertyChanged("cnccd")
				Me.OncnccdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cncrcvdate", DbType:="Date")>  _
	Public Property cncrcvdate() As System.Nullable(Of Date)
		Get
			Return Me._cncrcvdate
		End Get
		Set
			If (Me._cncrcvdate.Equals(value) = false) Then
				Me.OncncrcvdateChanging(value)
				Me.SendPropertyChanging
				Me._cncrcvdate = value
				Me.SendPropertyChanged("cncrcvdate")
				Me.OncncrcvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cncdate", DbType:="Date")>  _
	Public Property cncdate() As System.Nullable(Of Date)
		Get
			Return Me._cncdate
		End Get
		Set
			If (Me._cncdate.Equals(value) = false) Then
				Me.OncncdateChanging(value)
				Me.SendPropertyChanging
				Me._cncdate = value
				Me.SendPropertyChanged("cncdate")
				Me.OncncdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_causecd", DbType:="SmallInt")>  _
	Public Property causecd() As System.Nullable(Of Short)
		Get
			Return Me._causecd
		End Get
		Set
			If (Me._causecd.Equals(value) = false) Then
				Me.OncausecdChanging(value)
				Me.SendPropertyChanging
				Me._causecd = value
				Me.SendPropertyChanged("causecd")
				Me.OncausecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_document", DbType:="VarChar(60)")>  _
	Public Property document() As String
		Get
			Return Me._document
		End Get
		Set
			If (String.Equals(Me._document, value) = false) Then
				Me.OndocumentChanging(value)
				Me.SendPropertyChanging
				Me._document = value
				Me.SendPropertyChanged("document")
				Me.OndocumentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_amphrcd", DbType:="SmallInt")>  _
	Public Property amphrcd() As System.Nullable(Of Short)
		Get
			Return Me._amphrcd
		End Get
		Set
			If (Me._amphrcd.Equals(value) = false) Then
				Me.OnamphrcdChanging(value)
				Me.SendPropertyChanging
				Me._amphrcd = value
				Me.SendPropertyChanged("amphrcd")
				Me.OnamphrcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_chngwtcd", DbType:="SmallInt")>  _
	Public Property chngwtcd() As System.Nullable(Of Short)
		Get
			Return Me._chngwtcd
		End Get
		Set
			If (Me._chngwtcd.Equals(value) = false) Then
				Me.OnchngwtcdChanging(value)
				Me.SendPropertyChanging
				Me._chngwtcd = value
				Me.SendPropertyChanged("chngwtcd")
				Me.OnchngwtcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lstfcd", DbType:="Int")>  _
	Public Property lstfcd() As System.Nullable(Of Integer)
		Get
			Return Me._lstfcd
		End Get
		Set
			If (Me._lstfcd.Equals(value) = false) Then
				Me.OnlstfcdChanging(value)
				Me.SendPropertyChanging
				Me._lstfcd = value
				Me.SendPropertyChanged("lstfcd")
				Me.OnlstfcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lmdfdate", DbType:="DateTime2")>  _
	Public Property lmdfdate() As System.Nullable(Of Date)
		Get
			Return Me._lmdfdate
		End Get
		Set
			If (Me._lmdfdate.Equals(value) = false) Then
				Me.OnlmdfdateChanging(value)
				Me.SendPropertyChanging
				Me._lmdfdate = value
				Me.SendPropertyChanged("lmdfdate")
				Me.OnlmdfdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reflcnst", DbType:="Char(1)")>  _
	Public Property reflcnst() As System.Nullable(Of Char)
		Get
			Return Me._reflcnst
		End Get
		Set
			If (Me._reflcnst.Equals(value) = false) Then
				Me.OnreflcnstChanging(value)
				Me.SendPropertyChanging
				Me._reflcnst = value
				Me.SendPropertyChanged("reflcnst")
				Me.OnreflcnstChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_refappvtp", DbType:="Char(1)")>  _
	Public Property refappvtp() As System.Nullable(Of Char)
		Get
			Return Me._refappvtp
		End Get
		Set
			If (Me._refappvtp.Equals(value) = false) Then
				Me.OnrefappvtpChanging(value)
				Me.SendPropertyChanging
				Me._refappvtp = value
				Me.SendPropertyChanged("refappvtp")
				Me.OnrefappvtpChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reflcnpvncd", DbType:="SmallInt")>  _
	Public Property reflcnpvncd() As System.Nullable(Of Short)
		Get
			Return Me._reflcnpvncd
		End Get
		Set
			If (Me._reflcnpvncd.Equals(value) = false) Then
				Me.OnreflcnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._reflcnpvncd = value
				Me.SendPropertyChanged("reflcnpvncd")
				Me.OnreflcnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_reflcnno", DbType:="Int")>  _
	Public Property reflcnno() As System.Nullable(Of Integer)
		Get
			Return Me._reflcnno
		End Get
		Set
			If (Me._reflcnno.Equals(value) = false) Then
				Me.OnreflcnnoChanging(value)
				Me.SendPropertyChanging
				Me._reflcnno = value
				Me.SendPropertyChanged("reflcnno")
				Me.OnreflcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_refchngwtcd", DbType:="SmallInt")>  _
	Public Property refchngwtcd() As System.Nullable(Of Short)
		Get
			Return Me._refchngwtcd
		End Get
		Set
			If (Me._refchngwtcd.Equals(value) = false) Then
				Me.OnrefchngwtcdChanging(value)
				Me.SendPropertyChanging
				Me._refchngwtcd = value
				Me.SendPropertyChanged("refchngwtcd")
				Me.OnrefchngwtcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvno", DbType:="Int")>  _
	Public Property rcvno() As System.Nullable(Of Integer)
		Get
			Return Me._rcvno
		End Get
		Set
			If (Me._rcvno.Equals(value) = false) Then
				Me.OnrcvnoChanging(value)
				Me.SendPropertyChanging
				Me._rcvno = value
				Me.SendPropertyChanged("rcvno")
				Me.OnrcvnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvdate", DbType:="DateTime")>  _
	Public Property rcvdate() As System.Nullable(Of Date)
		Get
			Return Me._rcvdate
		End Get
		Set
			If (Me._rcvdate.Equals(value) = false) Then
				Me.OnrcvdateChanging(value)
				Me.SendPropertyChanging
				Me._rcvdate = value
				Me.SendPropertyChanged("rcvdate")
				Me.OnrcvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cnsdcd", DbType:="Int")>  _
	Public Property cnsdcd() As System.Nullable(Of Integer)
		Get
			Return Me._cnsdcd
		End Get
		Set
			If (Me._cnsdcd.Equals(value) = false) Then
				Me.OncnsdcdChanging(value)
				Me.SendPropertyChanging
				Me._cnsdcd = value
				Me.SendPropertyChanged("cnsdcd")
				Me.OncnsdcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_xmlnm", DbType:="NVarChar(MAX)")>  _
	Public Property xmlnm() As String
		Get
			Return Me._xmlnm
		End Get
		Set
			If (String.Equals(Me._xmlnm, value) = false) Then
				Me.OnxmlnmChanging(value)
				Me.SendPropertyChanging
				Me._xmlnm = value
				Me.SendPropertyChanged("xmlnm")
				Me.OnxmlnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TRANSECTION_ID_UPLOAD", DbType:="Int")>  _
	Public Property TRANSECTION_ID_UPLOAD() As System.Nullable(Of Integer)
		Get
			Return Me._TRANSECTION_ID_UPLOAD
		End Get
		Set
			If (Me._TRANSECTION_ID_UPLOAD.Equals(value) = false) Then
				Me.OnTRANSECTION_ID_UPLOADChanging(value)
				Me.SendPropertyChanging
				Me._TRANSECTION_ID_UPLOAD = value
				Me.SendPropertyChanged("TRANSECTION_ID_UPLOAD")
				Me.OnTRANSECTION_ID_UPLOADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID_UPLOAD", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID_UPLOAD() As String
		Get
			Return Me._CITIZEN_ID_UPLOAD
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID_UPLOAD, value) = false) Then
				Me.OnCITIZEN_ID_UPLOADChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID_UPLOAD = value
				Me.SendPropertyChanged("CITIZEN_ID_UPLOAD")
				Me.OnCITIZEN_ID_UPLOADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID_AUTHORIZE", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID_AUTHORIZE() As String
		Get
			Return Me._CITIZEN_ID_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID_AUTHORIZE, value) = false) Then
				Me.OnCITIZEN_ID_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID_AUTHORIZE = value
				Me.SendPropertyChanged("CITIZEN_ID_AUTHORIZE")
				Me.OnCITIZEN_ID_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CUS_EXPLAIN", DbType:="NVarChar(MAX)")>  _
	Public Property CUS_EXPLAIN() As String
		Get
			Return Me._CUS_EXPLAIN
		End Get
		Set
			If (String.Equals(Me._CUS_EXPLAIN, value) = false) Then
				Me.OnCUS_EXPLAINChanging(value)
				Me.SendPropertyChanging
				Me._CUS_EXPLAIN = value
				Me.SendPropertyChanged("CUS_EXPLAIN")
				Me.OnCUS_EXPLAINChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STAFF_EXPLAIN", DbType:="NVarChar(MAX)")>  _
	Public Property STAFF_EXPLAIN() As String
		Get
			Return Me._STAFF_EXPLAIN
		End Get
		Set
			If (String.Equals(Me._STAFF_EXPLAIN, value) = false) Then
				Me.OnSTAFF_EXPLAINChanging(value)
				Me.SendPropertyChanging
				Me._STAFF_EXPLAIN = value
				Me.SendPropertyChanged("STAFF_EXPLAIN")
				Me.OnSTAFF_EXPLAINChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAYMENT_REPAIR", DbType:="Int")>  _
	Public Property PAYMENT_REPAIR() As System.Nullable(Of Integer)
		Get
			Return Me._PAYMENT_REPAIR
		End Get
		Set
			If (Me._PAYMENT_REPAIR.Equals(value) = false) Then
				Me.OnPAYMENT_REPAIRChanging(value)
				Me.SendPropertyChanging
				Me._PAYMENT_REPAIR = value
				Me.SendPropertyChanged("PAYMENT_REPAIR")
				Me.OnPAYMENT_REPAIRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CB_TYPE", DbType:="Int")>  _
	Public Property CB_TYPE() As System.Nullable(Of Integer)
		Get
			Return Me._CB_TYPE
		End Get
		Set
			If (Me._CB_TYPE.Equals(value) = false) Then
				Me.OnCB_TYPEChanging(value)
				Me.SendPropertyChanging
				Me._CB_TYPE = value
				Me.SendPropertyChanged("CB_TYPE")
				Me.OnCB_TYPEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CB_CODE", DbType:="NVarChar(MAX)")>  _
	Public Property CB_CODE() As String
		Get
			Return Me._CB_CODE
		End Get
		Set
			If (String.Equals(Me._CB_CODE, value) = false) Then
				Me.OnCB_CODEChanging(value)
				Me.SendPropertyChanging
				Me._CB_CODE = value
				Me.SendPropertyChanged("CB_CODE")
				Me.OnCB_CODEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CB_ID_AUTHORIZE", DbType:="NVarChar(MAX)")>  _
	Public Property CB_ID_AUTHORIZE() As String
		Get
			Return Me._CB_ID_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CB_ID_AUTHORIZE, value) = false) Then
				Me.OnCB_ID_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CB_ID_AUTHORIZE = value
				Me.SendPropertyChanged("CB_ID_AUTHORIZE")
				Me.OnCB_ID_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AUDIT_TR_ID", DbType:="Int")>  _
	Public Property AUDIT_TR_ID() As System.Nullable(Of Integer)
		Get
			Return Me._AUDIT_TR_ID
		End Get
		Set
			If (Me._AUDIT_TR_ID.Equals(value) = false) Then
				Me.OnAUDIT_TR_IDChanging(value)
				Me.SendPropertyChanging
				Me._AUDIT_TR_ID = value
				Me.SendPropertyChanged("AUDIT_TR_ID")
				Me.OnAUDIT_TR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AUDIT_XMLNAME", DbType:="NVarChar(MAX)")>  _
	Public Property AUDIT_XMLNAME() As String
		Get
			Return Me._AUDIT_XMLNAME
		End Get
		Set
			If (String.Equals(Me._AUDIT_XMLNAME, value) = false) Then
				Me.OnAUDIT_XMLNAMEChanging(value)
				Me.SendPropertyChanging
				Me._AUDIT_XMLNAME = value
				Me.SendPropertyChanged("AUDIT_XMLNAME")
				Me.OnAUDIT_XMLNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AUDIT_UPLOAD_CITIZEN", DbType:="NVarChar(MAX)")>  _
	Public Property AUDIT_UPLOAD_CITIZEN() As String
		Get
			Return Me._AUDIT_UPLOAD_CITIZEN
		End Get
		Set
			If (String.Equals(Me._AUDIT_UPLOAD_CITIZEN, value) = false) Then
				Me.OnAUDIT_UPLOAD_CITIZENChanging(value)
				Me.SendPropertyChanging
				Me._AUDIT_UPLOAD_CITIZEN = value
				Me.SendPropertyChanged("AUDIT_UPLOAD_CITIZEN")
				Me.OnAUDIT_UPLOAD_CITIZENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AUDIT_UPLOAD_DATE", DbType:="NVarChar(MAX)")>  _
	Public Property AUDIT_UPLOAD_DATE() As String
		Get
			Return Me._AUDIT_UPLOAD_DATE
		End Get
		Set
			If (String.Equals(Me._AUDIT_UPLOAD_DATE, value) = false) Then
				Me.OnAUDIT_UPLOAD_DATEChanging(value)
				Me.SendPropertyChanging
				Me._AUDIT_UPLOAD_DATE = value
				Me.SendPropertyChanged("AUDIT_UPLOAD_DATE")
				Me.OnAUDIT_UPLOAD_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MONITOR_TR_ID", DbType:="Int")>  _
	Public Property MONITOR_TR_ID() As System.Nullable(Of Integer)
		Get
			Return Me._MONITOR_TR_ID
		End Get
		Set
			If (Me._MONITOR_TR_ID.Equals(value) = false) Then
				Me.OnMONITOR_TR_IDChanging(value)
				Me.SendPropertyChanging
				Me._MONITOR_TR_ID = value
				Me.SendPropertyChanged("MONITOR_TR_ID")
				Me.OnMONITOR_TR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MONITOR_XMLNAME", DbType:="NVarChar(MAX)")>  _
	Public Property MONITOR_XMLNAME() As String
		Get
			Return Me._MONITOR_XMLNAME
		End Get
		Set
			If (String.Equals(Me._MONITOR_XMLNAME, value) = false) Then
				Me.OnMONITOR_XMLNAMEChanging(value)
				Me.SendPropertyChanging
				Me._MONITOR_XMLNAME = value
				Me.SendPropertyChanged("MONITOR_XMLNAME")
				Me.OnMONITOR_XMLNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MONITOR_UPLOAD_CITIZEN", DbType:="NVarChar(MAX)")>  _
	Public Property MONITOR_UPLOAD_CITIZEN() As String
		Get
			Return Me._MONITOR_UPLOAD_CITIZEN
		End Get
		Set
			If (String.Equals(Me._MONITOR_UPLOAD_CITIZEN, value) = false) Then
				Me.OnMONITOR_UPLOAD_CITIZENChanging(value)
				Me.SendPropertyChanging
				Me._MONITOR_UPLOAD_CITIZEN = value
				Me.SendPropertyChanged("MONITOR_UPLOAD_CITIZEN")
				Me.OnMONITOR_UPLOAD_CITIZENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MONITOR_UPLOAD_DATE", DbType:="DateTime")>  _
	Public Property MONITOR_UPLOAD_DATE() As System.Nullable(Of Date)
		Get
			Return Me._MONITOR_UPLOAD_DATE
		End Get
		Set
			If (Me._MONITOR_UPLOAD_DATE.Equals(value) = false) Then
				Me.OnMONITOR_UPLOAD_DATEChanging(value)
				Me.SendPropertyChanging
				Me._MONITOR_UPLOAD_DATE = value
				Me.SendPropertyChanged("MONITOR_UPLOAD_DATE")
				Me.OnMONITOR_UPLOAD_DATEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.fabsncdtlcn")>  _
Partial Public Class fabsncdtlcn
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _pvncd As System.Nullable(Of Short)
	
	Private _lcntypecd As System.Nullable(Of Short)
	
	Private _lcnno As System.Nullable(Of Integer)
	
	Private _cdtno As System.Nullable(Of Integer)
	
	Private _rid As System.Nullable(Of Integer)
	
	Private _bsncd As System.Nullable(Of Integer)
	
	Private _NAME As String
	
	Private _CITIZEN_NO As String
	
	Private _TR_ID As System.Nullable(Of Integer)
	
	Private _FK_IDA As System.Nullable(Of Integer)
	
	Private _LAW_TXT As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlcntypecdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlcntypecdChanged()
    End Sub
    Partial Private Sub OnlcnnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnnoChanged()
    End Sub
    Partial Private Sub OncdtnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncdtnoChanged()
    End Sub
    Partial Private Sub OnridChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnridChanged()
    End Sub
    Partial Private Sub OnbsncdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnbsncdChanged()
    End Sub
    Partial Private Sub OnNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnNAMEChanged()
    End Sub
    Partial Private Sub OnCITIZEN_NOChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_NOChanged()
    End Sub
    Partial Private Sub OnTR_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTR_IDChanged()
    End Sub
    Partial Private Sub OnFK_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_IDAChanged()
    End Sub
    Partial Private Sub OnLAW_TXTChanging(value As String)
    End Sub
    Partial Private Sub OnLAW_TXTChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="SmallInt")>  _
	Public Property pvncd() As System.Nullable(Of Short)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypecd", DbType:="SmallInt")>  _
	Public Property lcntypecd() As System.Nullable(Of Short)
		Get
			Return Me._lcntypecd
		End Get
		Set
			If (Me._lcntypecd.Equals(value) = false) Then
				Me.OnlcntypecdChanging(value)
				Me.SendPropertyChanging
				Me._lcntypecd = value
				Me.SendPropertyChanged("lcntypecd")
				Me.OnlcntypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnno", DbType:="Int")>  _
	Public Property lcnno() As System.Nullable(Of Integer)
		Get
			Return Me._lcnno
		End Get
		Set
			If (Me._lcnno.Equals(value) = false) Then
				Me.OnlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lcnno = value
				Me.SendPropertyChanged("lcnno")
				Me.OnlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cdtno", DbType:="Int")>  _
	Public Property cdtno() As System.Nullable(Of Integer)
		Get
			Return Me._cdtno
		End Get
		Set
			If (Me._cdtno.Equals(value) = false) Then
				Me.OncdtnoChanging(value)
				Me.SendPropertyChanging
				Me._cdtno = value
				Me.SendPropertyChanged("cdtno")
				Me.OncdtnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rid", DbType:="Int")>  _
	Public Property rid() As System.Nullable(Of Integer)
		Get
			Return Me._rid
		End Get
		Set
			If (Me._rid.Equals(value) = false) Then
				Me.OnridChanging(value)
				Me.SendPropertyChanging
				Me._rid = value
				Me.SendPropertyChanged("rid")
				Me.OnridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_bsncd", DbType:="Int")>  _
	Public Property bsncd() As System.Nullable(Of Integer)
		Get
			Return Me._bsncd
		End Get
		Set
			If (Me._bsncd.Equals(value) = false) Then
				Me.OnbsncdChanging(value)
				Me.SendPropertyChanging
				Me._bsncd = value
				Me.SendPropertyChanged("bsncd")
				Me.OnbsncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property NAME() As String
		Get
			Return Me._NAME
		End Get
		Set
			If (String.Equals(Me._NAME, value) = false) Then
				Me.OnNAMEChanging(value)
				Me.SendPropertyChanging
				Me._NAME = value
				Me.SendPropertyChanged("NAME")
				Me.OnNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_NO", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_NO() As String
		Get
			Return Me._CITIZEN_NO
		End Get
		Set
			If (String.Equals(Me._CITIZEN_NO, value) = false) Then
				Me.OnCITIZEN_NOChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_NO = value
				Me.SendPropertyChanged("CITIZEN_NO")
				Me.OnCITIZEN_NOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TR_ID", DbType:="Int")>  _
	Public Property TR_ID() As System.Nullable(Of Integer)
		Get
			Return Me._TR_ID
		End Get
		Set
			If (Me._TR_ID.Equals(value) = false) Then
				Me.OnTR_IDChanging(value)
				Me.SendPropertyChanging
				Me._TR_ID = value
				Me.SendPropertyChanged("TR_ID")
				Me.OnTR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_IDA", DbType:="Int")>  _
	Public Property FK_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FK_IDA
		End Get
		Set
			If (Me._FK_IDA.Equals(value) = false) Then
				Me.OnFK_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FK_IDA = value
				Me.SendPropertyChanged("FK_IDA")
				Me.OnFK_IDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAW_TXT", DbType:="NVarChar(MAX)")>  _
	Public Property LAW_TXT() As String
		Get
			Return Me._LAW_TXT
		End Get
		Set
			If (String.Equals(Me._LAW_TXT, value) = false) Then
				Me.OnLAW_TXTChanging(value)
				Me.SendPropertyChanging
				Me._LAW_TXT = value
				Me.SendPropertyChanged("LAW_TXT")
				Me.OnLAW_TXTChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.falcnaddr")>  _
Partial Public Class falcnaddr
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _trans_ID As System.Nullable(Of Integer)
	
	Private _nameplace As String
	
	Private _number_addr As String
	
	Private _room As String
	
	Private _moo As String
	
	Private _floor As String
	
	Private _soi As String
	
	Private _building As String
	
	Private _road As String
	
	Private _thmblcd As System.Nullable(Of Integer)
	
	Private _amphrcd As System.Nullable(Of Integer)
	
	Private _chngwtcd As System.Nullable(Of Integer)
	
	Private _zipcode As String
	
	Private _tel_home As String
	
	Private _tel_telephone As String
	
	Private _house_no As String
	
	Private _lcnno As String
	
	Private _lcntypecd As System.Nullable(Of Integer)
	
	Private _pvncd As System.Nullable(Of Integer)
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _FK_IDA As System.Nullable(Of Integer)
	
	Private _chngwtname As String
	
	Private _amphrname As String
	
	Private _thmblname As String
	
	Private _MAIN_GROUP As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub Ontrans_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Ontrans_IDChanged()
    End Sub
    Partial Private Sub OnnameplaceChanging(value As String)
    End Sub
    Partial Private Sub OnnameplaceChanged()
    End Sub
    Partial Private Sub Onnumber_addrChanging(value As String)
    End Sub
    Partial Private Sub Onnumber_addrChanged()
    End Sub
    Partial Private Sub OnroomChanging(value As String)
    End Sub
    Partial Private Sub OnroomChanged()
    End Sub
    Partial Private Sub OnmooChanging(value As String)
    End Sub
    Partial Private Sub OnmooChanged()
    End Sub
    Partial Private Sub OnfloorChanging(value As String)
    End Sub
    Partial Private Sub OnfloorChanged()
    End Sub
    Partial Private Sub OnsoiChanging(value As String)
    End Sub
    Partial Private Sub OnsoiChanged()
    End Sub
    Partial Private Sub OnbuildingChanging(value As String)
    End Sub
    Partial Private Sub OnbuildingChanged()
    End Sub
    Partial Private Sub OnroadChanging(value As String)
    End Sub
    Partial Private Sub OnroadChanged()
    End Sub
    Partial Private Sub OnthmblcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnthmblcdChanged()
    End Sub
    Partial Private Sub OnamphrcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnamphrcdChanged()
    End Sub
    Partial Private Sub OnchngwtcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnchngwtcdChanged()
    End Sub
    Partial Private Sub OnzipcodeChanging(value As String)
    End Sub
    Partial Private Sub OnzipcodeChanged()
    End Sub
    Partial Private Sub Ontel_homeChanging(value As String)
    End Sub
    Partial Private Sub Ontel_homeChanged()
    End Sub
    Partial Private Sub Ontel_telephoneChanging(value As String)
    End Sub
    Partial Private Sub Ontel_telephoneChanged()
    End Sub
    Partial Private Sub Onhouse_noChanging(value As String)
    End Sub
    Partial Private Sub Onhouse_noChanged()
    End Sub
    Partial Private Sub OnlcnnoChanging(value As String)
    End Sub
    Partial Private Sub OnlcnnoChanged()
    End Sub
    Partial Private Sub OnlcntypecdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcntypecdChanged()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnFK_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_IDAChanged()
    End Sub
    Partial Private Sub OnchngwtnameChanging(value As String)
    End Sub
    Partial Private Sub OnchngwtnameChanged()
    End Sub
    Partial Private Sub OnamphrnameChanging(value As String)
    End Sub
    Partial Private Sub OnamphrnameChanged()
    End Sub
    Partial Private Sub OnthmblnameChanging(value As String)
    End Sub
    Partial Private Sub OnthmblnameChanged()
    End Sub
    Partial Private Sub OnMAIN_GROUPChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMAIN_GROUPChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_trans_ID", DbType:="Int")>  _
	Public Property trans_ID() As System.Nullable(Of Integer)
		Get
			Return Me._trans_ID
		End Get
		Set
			If (Me._trans_ID.Equals(value) = false) Then
				Me.Ontrans_IDChanging(value)
				Me.SendPropertyChanging
				Me._trans_ID = value
				Me.SendPropertyChanged("trans_ID")
				Me.Ontrans_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_nameplace", DbType:="VarChar(MAX)")>  _
	Public Property nameplace() As String
		Get
			Return Me._nameplace
		End Get
		Set
			If (String.Equals(Me._nameplace, value) = false) Then
				Me.OnnameplaceChanging(value)
				Me.SendPropertyChanging
				Me._nameplace = value
				Me.SendPropertyChanged("nameplace")
				Me.OnnameplaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_number_addr", DbType:="VarChar(MAX)")>  _
	Public Property number_addr() As String
		Get
			Return Me._number_addr
		End Get
		Set
			If (String.Equals(Me._number_addr, value) = false) Then
				Me.Onnumber_addrChanging(value)
				Me.SendPropertyChanging
				Me._number_addr = value
				Me.SendPropertyChanged("number_addr")
				Me.Onnumber_addrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_room", DbType:="VarChar(MAX)")>  _
	Public Property room() As String
		Get
			Return Me._room
		End Get
		Set
			If (String.Equals(Me._room, value) = false) Then
				Me.OnroomChanging(value)
				Me.SendPropertyChanging
				Me._room = value
				Me.SendPropertyChanged("room")
				Me.OnroomChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_moo", DbType:="VarChar(MAX)")>  _
	Public Property moo() As String
		Get
			Return Me._moo
		End Get
		Set
			If (String.Equals(Me._moo, value) = false) Then
				Me.OnmooChanging(value)
				Me.SendPropertyChanging
				Me._moo = value
				Me.SendPropertyChanged("moo")
				Me.OnmooChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_floor", DbType:="VarChar(MAX)")>  _
	Public Property floor() As String
		Get
			Return Me._floor
		End Get
		Set
			If (String.Equals(Me._floor, value) = false) Then
				Me.OnfloorChanging(value)
				Me.SendPropertyChanging
				Me._floor = value
				Me.SendPropertyChanged("floor")
				Me.OnfloorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_soi", DbType:="VarChar(MAX)")>  _
	Public Property soi() As String
		Get
			Return Me._soi
		End Get
		Set
			If (String.Equals(Me._soi, value) = false) Then
				Me.OnsoiChanging(value)
				Me.SendPropertyChanging
				Me._soi = value
				Me.SendPropertyChanged("soi")
				Me.OnsoiChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_building", DbType:="VarChar(MAX)")>  _
	Public Property building() As String
		Get
			Return Me._building
		End Get
		Set
			If (String.Equals(Me._building, value) = false) Then
				Me.OnbuildingChanging(value)
				Me.SendPropertyChanging
				Me._building = value
				Me.SendPropertyChanged("building")
				Me.OnbuildingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_road", DbType:="VarChar(MAX)")>  _
	Public Property road() As String
		Get
			Return Me._road
		End Get
		Set
			If (String.Equals(Me._road, value) = false) Then
				Me.OnroadChanging(value)
				Me.SendPropertyChanging
				Me._road = value
				Me.SendPropertyChanged("road")
				Me.OnroadChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thmblcd", DbType:="Int")>  _
	Public Property thmblcd() As System.Nullable(Of Integer)
		Get
			Return Me._thmblcd
		End Get
		Set
			If (Me._thmblcd.Equals(value) = false) Then
				Me.OnthmblcdChanging(value)
				Me.SendPropertyChanging
				Me._thmblcd = value
				Me.SendPropertyChanged("thmblcd")
				Me.OnthmblcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_amphrcd", DbType:="Int")>  _
	Public Property amphrcd() As System.Nullable(Of Integer)
		Get
			Return Me._amphrcd
		End Get
		Set
			If (Me._amphrcd.Equals(value) = false) Then
				Me.OnamphrcdChanging(value)
				Me.SendPropertyChanging
				Me._amphrcd = value
				Me.SendPropertyChanged("amphrcd")
				Me.OnamphrcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_chngwtcd", DbType:="Int")>  _
	Public Property chngwtcd() As System.Nullable(Of Integer)
		Get
			Return Me._chngwtcd
		End Get
		Set
			If (Me._chngwtcd.Equals(value) = false) Then
				Me.OnchngwtcdChanging(value)
				Me.SendPropertyChanging
				Me._chngwtcd = value
				Me.SendPropertyChanged("chngwtcd")
				Me.OnchngwtcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_zipcode", DbType:="NVarChar(50)")>  _
	Public Property zipcode() As String
		Get
			Return Me._zipcode
		End Get
		Set
			If (String.Equals(Me._zipcode, value) = false) Then
				Me.OnzipcodeChanging(value)
				Me.SendPropertyChanging
				Me._zipcode = value
				Me.SendPropertyChanged("zipcode")
				Me.OnzipcodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tel_home", DbType:="VarChar(MAX)")>  _
	Public Property tel_home() As String
		Get
			Return Me._tel_home
		End Get
		Set
			If (String.Equals(Me._tel_home, value) = false) Then
				Me.Ontel_homeChanging(value)
				Me.SendPropertyChanging
				Me._tel_home = value
				Me.SendPropertyChanged("tel_home")
				Me.Ontel_homeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tel_telephone", DbType:="VarChar(MAX)")>  _
	Public Property tel_telephone() As String
		Get
			Return Me._tel_telephone
		End Get
		Set
			If (String.Equals(Me._tel_telephone, value) = false) Then
				Me.Ontel_telephoneChanging(value)
				Me.SendPropertyChanging
				Me._tel_telephone = value
				Me.SendPropertyChanged("tel_telephone")
				Me.Ontel_telephoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_house_no", DbType:="VarChar(MAX)")>  _
	Public Property house_no() As String
		Get
			Return Me._house_no
		End Get
		Set
			If (String.Equals(Me._house_no, value) = false) Then
				Me.Onhouse_noChanging(value)
				Me.SendPropertyChanging
				Me._house_no = value
				Me.SendPropertyChanged("house_no")
				Me.Onhouse_noChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnno", DbType:="NVarChar(MAX)")>  _
	Public Property lcnno() As String
		Get
			Return Me._lcnno
		End Get
		Set
			If (String.Equals(Me._lcnno, value) = false) Then
				Me.OnlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lcnno = value
				Me.SendPropertyChanged("lcnno")
				Me.OnlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypecd", DbType:="Int")>  _
	Public Property lcntypecd() As System.Nullable(Of Integer)
		Get
			Return Me._lcntypecd
		End Get
		Set
			If (Me._lcntypecd.Equals(value) = false) Then
				Me.OnlcntypecdChanging(value)
				Me.SendPropertyChanging
				Me._lcntypecd = value
				Me.SendPropertyChanged("lcntypecd")
				Me.OnlcntypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="Int")>  _
	Public Property pvncd() As System.Nullable(Of Integer)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_IDA", DbType:="Int")>  _
	Public Property FK_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FK_IDA
		End Get
		Set
			If (Me._FK_IDA.Equals(value) = false) Then
				Me.OnFK_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FK_IDA = value
				Me.SendPropertyChanged("FK_IDA")
				Me.OnFK_IDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_chngwtname", DbType:="NVarChar(MAX)")>  _
	Public Property chngwtname() As String
		Get
			Return Me._chngwtname
		End Get
		Set
			If (String.Equals(Me._chngwtname, value) = false) Then
				Me.OnchngwtnameChanging(value)
				Me.SendPropertyChanging
				Me._chngwtname = value
				Me.SendPropertyChanged("chngwtname")
				Me.OnchngwtnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_amphrname", DbType:="NVarChar(MAX)")>  _
	Public Property amphrname() As String
		Get
			Return Me._amphrname
		End Get
		Set
			If (String.Equals(Me._amphrname, value) = false) Then
				Me.OnamphrnameChanging(value)
				Me.SendPropertyChanging
				Me._amphrname = value
				Me.SendPropertyChanged("amphrname")
				Me.OnamphrnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thmblname", DbType:="NVarChar(MAX)")>  _
	Public Property thmblname() As String
		Get
			Return Me._thmblname
		End Get
		Set
			If (String.Equals(Me._thmblname, value) = false) Then
				Me.OnthmblnameChanging(value)
				Me.SendPropertyChanging
				Me._thmblname = value
				Me.SendPropertyChanged("thmblname")
				Me.OnthmblnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MAIN_GROUP", DbType:="Int")>  _
	Public Property MAIN_GROUP() As System.Nullable(Of Integer)
		Get
			Return Me._MAIN_GROUP
		End Get
		Set
			If (Me._MAIN_GROUP.Equals(value) = false) Then
				Me.OnMAIN_GROUPChanging(value)
				Me.SendPropertyChanging
				Me._MAIN_GROUP = value
				Me.SendPropertyChanged("MAIN_GROUP")
				Me.OnMAIN_GROUPChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.flabelinitial")>  _
Partial Public Class flabelinitial
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _compvncd As System.Nullable(Of Short)
	
	Private _comabbr As String
	
	Private _comno As System.Nullable(Of Integer)
	
	Private _rid As System.Nullable(Of Short)
	
	Private _initial As String
	
	Private _TR_ID As System.Nullable(Of Integer)
	
	Private _FR_IDA As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OncompvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OncompvncdChanged()
    End Sub
    Partial Private Sub OncomabbrChanging(value As String)
    End Sub
    Partial Private Sub OncomabbrChanged()
    End Sub
    Partial Private Sub OncomnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncomnoChanged()
    End Sub
    Partial Private Sub OnridChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnridChanged()
    End Sub
    Partial Private Sub OninitialChanging(value As String)
    End Sub
    Partial Private Sub OninitialChanged()
    End Sub
    Partial Private Sub OnTR_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTR_IDChanged()
    End Sub
    Partial Private Sub OnFR_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFR_IDAChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_compvncd", DbType:="SmallInt")>  _
	Public Property compvncd() As System.Nullable(Of Short)
		Get
			Return Me._compvncd
		End Get
		Set
			If (Me._compvncd.Equals(value) = false) Then
				Me.OncompvncdChanging(value)
				Me.SendPropertyChanging
				Me._compvncd = value
				Me.SendPropertyChanged("compvncd")
				Me.OncompvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_comabbr", DbType:="VarChar(10)")>  _
	Public Property comabbr() As String
		Get
			Return Me._comabbr
		End Get
		Set
			If (String.Equals(Me._comabbr, value) = false) Then
				Me.OncomabbrChanging(value)
				Me.SendPropertyChanging
				Me._comabbr = value
				Me.SendPropertyChanged("comabbr")
				Me.OncomabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_comno", DbType:="Int")>  _
	Public Property comno() As System.Nullable(Of Integer)
		Get
			Return Me._comno
		End Get
		Set
			If (Me._comno.Equals(value) = false) Then
				Me.OncomnoChanging(value)
				Me.SendPropertyChanging
				Me._comno = value
				Me.SendPropertyChanged("comno")
				Me.OncomnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rid", DbType:="SmallInt")>  _
	Public Property rid() As System.Nullable(Of Short)
		Get
			Return Me._rid
		End Get
		Set
			If (Me._rid.Equals(value) = false) Then
				Me.OnridChanging(value)
				Me.SendPropertyChanging
				Me._rid = value
				Me.SendPropertyChanged("rid")
				Me.OnridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_initial", DbType:="VarChar(255)")>  _
	Public Property initial() As String
		Get
			Return Me._initial
		End Get
		Set
			If (String.Equals(Me._initial, value) = false) Then
				Me.OninitialChanging(value)
				Me.SendPropertyChanging
				Me._initial = value
				Me.SendPropertyChanged("initial")
				Me.OninitialChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TR_ID", DbType:="Int")>  _
	Public Property TR_ID() As System.Nullable(Of Integer)
		Get
			Return Me._TR_ID
		End Get
		Set
			If (Me._TR_ID.Equals(value) = false) Then
				Me.OnTR_IDChanging(value)
				Me.SendPropertyChanging
				Me._TR_ID = value
				Me.SendPropertyChanged("TR_ID")
				Me.OnTR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FR_IDA", DbType:="Int")>  _
	Public Property FR_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FR_IDA
		End Get
		Set
			If (Me._FR_IDA.Equals(value) = false) Then
				Me.OnFR_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FR_IDA = value
				Me.SendPropertyChanged("FR_IDA")
				Me.OnFR_IDAChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.fafdtype")>  _
Partial Public Class fafdtype
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _fdtypecd As System.Nullable(Of Short)
	
	Private _fdtypenm As String
	
	Private _engnm As String
	
	Private _proregabbr As String
	
	Private _impregabbr As String
	
	Private _prolababbr As String
	
	Private _implababbr As String
	
	Private _expregabbr As String
	
	Private _explababbr As String
	
	Private _grptypecd As System.Nullable(Of Char)
	
	Private _gmpst As System.Nullable(Of Short)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnfdtypecdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnfdtypecdChanged()
    End Sub
    Partial Private Sub OnfdtypenmChanging(value As String)
    End Sub
    Partial Private Sub OnfdtypenmChanged()
    End Sub
    Partial Private Sub OnengnmChanging(value As String)
    End Sub
    Partial Private Sub OnengnmChanged()
    End Sub
    Partial Private Sub OnproregabbrChanging(value As String)
    End Sub
    Partial Private Sub OnproregabbrChanged()
    End Sub
    Partial Private Sub OnimpregabbrChanging(value As String)
    End Sub
    Partial Private Sub OnimpregabbrChanged()
    End Sub
    Partial Private Sub OnprolababbrChanging(value As String)
    End Sub
    Partial Private Sub OnprolababbrChanged()
    End Sub
    Partial Private Sub OnimplababbrChanging(value As String)
    End Sub
    Partial Private Sub OnimplababbrChanged()
    End Sub
    Partial Private Sub OnexpregabbrChanging(value As String)
    End Sub
    Partial Private Sub OnexpregabbrChanged()
    End Sub
    Partial Private Sub OnexplababbrChanging(value As String)
    End Sub
    Partial Private Sub OnexplababbrChanged()
    End Sub
    Partial Private Sub OngrptypecdChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OngrptypecdChanged()
    End Sub
    Partial Private Sub OngmpstChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OngmpstChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdtypecd", DbType:="SmallInt")>  _
	Public Property fdtypecd() As System.Nullable(Of Short)
		Get
			Return Me._fdtypecd
		End Get
		Set
			If (Me._fdtypecd.Equals(value) = false) Then
				Me.OnfdtypecdChanging(value)
				Me.SendPropertyChanging
				Me._fdtypecd = value
				Me.SendPropertyChanged("fdtypecd")
				Me.OnfdtypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdtypenm", DbType:="VarChar(150)")>  _
	Public Property fdtypenm() As String
		Get
			Return Me._fdtypenm
		End Get
		Set
			If (String.Equals(Me._fdtypenm, value) = false) Then
				Me.OnfdtypenmChanging(value)
				Me.SendPropertyChanging
				Me._fdtypenm = value
				Me.SendPropertyChanged("fdtypenm")
				Me.OnfdtypenmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engnm", DbType:="VarChar(150)")>  _
	Public Property engnm() As String
		Get
			Return Me._engnm
		End Get
		Set
			If (String.Equals(Me._engnm, value) = false) Then
				Me.OnengnmChanging(value)
				Me.SendPropertyChanging
				Me._engnm = value
				Me.SendPropertyChanged("engnm")
				Me.OnengnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_proregabbr", DbType:="VarChar(10)")>  _
	Public Property proregabbr() As String
		Get
			Return Me._proregabbr
		End Get
		Set
			If (String.Equals(Me._proregabbr, value) = false) Then
				Me.OnproregabbrChanging(value)
				Me.SendPropertyChanging
				Me._proregabbr = value
				Me.SendPropertyChanged("proregabbr")
				Me.OnproregabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_impregabbr", DbType:="VarChar(10)")>  _
	Public Property impregabbr() As String
		Get
			Return Me._impregabbr
		End Get
		Set
			If (String.Equals(Me._impregabbr, value) = false) Then
				Me.OnimpregabbrChanging(value)
				Me.SendPropertyChanging
				Me._impregabbr = value
				Me.SendPropertyChanged("impregabbr")
				Me.OnimpregabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prolababbr", DbType:="VarChar(10)")>  _
	Public Property prolababbr() As String
		Get
			Return Me._prolababbr
		End Get
		Set
			If (String.Equals(Me._prolababbr, value) = false) Then
				Me.OnprolababbrChanging(value)
				Me.SendPropertyChanging
				Me._prolababbr = value
				Me.SendPropertyChanged("prolababbr")
				Me.OnprolababbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_implababbr", DbType:="VarChar(10)")>  _
	Public Property implababbr() As String
		Get
			Return Me._implababbr
		End Get
		Set
			If (String.Equals(Me._implababbr, value) = false) Then
				Me.OnimplababbrChanging(value)
				Me.SendPropertyChanging
				Me._implababbr = value
				Me.SendPropertyChanged("implababbr")
				Me.OnimplababbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expregabbr", DbType:="VarChar(10)")>  _
	Public Property expregabbr() As String
		Get
			Return Me._expregabbr
		End Get
		Set
			If (String.Equals(Me._expregabbr, value) = false) Then
				Me.OnexpregabbrChanging(value)
				Me.SendPropertyChanging
				Me._expregabbr = value
				Me.SendPropertyChanged("expregabbr")
				Me.OnexpregabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_explababbr", DbType:="VarChar(10)")>  _
	Public Property explababbr() As String
		Get
			Return Me._explababbr
		End Get
		Set
			If (String.Equals(Me._explababbr, value) = false) Then
				Me.OnexplababbrChanging(value)
				Me.SendPropertyChanging
				Me._explababbr = value
				Me.SendPropertyChanged("explababbr")
				Me.OnexplababbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_grptypecd", DbType:="Char(1)")>  _
	Public Property grptypecd() As System.Nullable(Of Char)
		Get
			Return Me._grptypecd
		End Get
		Set
			If (Me._grptypecd.Equals(value) = false) Then
				Me.OngrptypecdChanging(value)
				Me.SendPropertyChanging
				Me._grptypecd = value
				Me.SendPropertyChanged("grptypecd")
				Me.OngrptypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_gmpst", DbType:="SmallInt")>  _
	Public Property gmpst() As System.Nullable(Of Short)
		Get
			Return Me._gmpst
		End Get
		Set
			If (Me._gmpst.Equals(value) = false) Then
				Me.OngmpstChanging(value)
				Me.SendPropertyChanging
				Me._gmpst = value
				Me.SendPropertyChanged("gmpst")
				Me.OngmpstChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="fda.falcntype")>  _
Partial Public Class falcntype
	
	Private _lcntypecd As Short
	
	Private _lcntypenm As String
	
	Private _engnm As String
	
	Private _rqtabbr As String
	
	Private _lcnabbr As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypecd", DbType:="SmallInt NOT NULL")>  _
	Public Property lcntypecd() As Short
		Get
			Return Me._lcntypecd
		End Get
		Set
			If ((Me._lcntypecd = value)  _
						= false) Then
				Me._lcntypecd = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypenm", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property lcntypenm() As String
		Get
			Return Me._lcntypenm
		End Get
		Set
			If (String.Equals(Me._lcntypenm, value) = false) Then
				Me._lcntypenm = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engnm", DbType:="VarChar(50)")>  _
	Public Property engnm() As String
		Get
			Return Me._engnm
		End Get
		Set
			If (String.Equals(Me._engnm, value) = false) Then
				Me._engnm = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rqtabbr", DbType:="Char(3)")>  _
	Public Property rqtabbr() As String
		Get
			Return Me._rqtabbr
		End Get
		Set
			If (String.Equals(Me._rqtabbr, value) = false) Then
				Me._rqtabbr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnabbr", DbType:="Char(3)")>  _
	Public Property lcnabbr() As String
		Get
			Return Me._lcnabbr
		End Get
		Set
			If (String.Equals(Me._lcnabbr, value) = false) Then
				Me._lcnabbr = value
			End If
		End Set
	End Property
End Class
