<?xml version="1.0" encoding="utf-8"?><Database Name="LGTCPN" Class="Linq_CPNDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.103;Initial Catalog=LGTCPN;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LGTCPNConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="fda.sysaddrhn" Member="sysaddrhns">
    <Type Name="sysaddrhn">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="houseno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.systhmbl" Member="systhmbls">
    <Type Name="systhmbl">
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="thmblcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="thathmblnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="engthmblnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="mapgis" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.sysamphr" Member="sysamphrs">
    <Type Name="sysamphr">
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="thaamphrnm" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="engamphrnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="mapgis" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syschngwt" Member="syschngwts">
    <Type Name="syschngwt">
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="thachngwtnm" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="engchngwtnm" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="thacwabbr" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="engcwabbr" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="mapgis" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="chngwtgrpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.sysgrpjpctype" Member="sysgrpjpctypes">
    <Type Name="sysgrpjpctype">
      <Column Name="grpjpctpcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="grpjpctpnm" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pdttpcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.sysidtelsms" Member="sysidtelsms">
    <Type Name="sysidtelsm">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="telsms" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.sysjpctype" Member="sysjpctypes">
    <Type Name="sysjpctype">
      <Column Name="jpctpcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="jpctpnm" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="jpcyear" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="jpcabbr" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="jpcst" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="stdno" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="notice1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="notice2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="orderno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rqttpcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="grpjpctpcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.syskplct" Member="syskplcts">
    <Type Name="syskplct">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lctnmcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="kplctcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cmtpdttp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.syslcnsasgn" Member="syslcnsasgns">
    <Type Name="syslcnsasgn">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="asgnid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="asgntpcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.syslcnsid" Member="syslcnsids">
    <Type Name="syslcnsid">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="identify" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="crtlct" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ntcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="taxno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="trdregno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ctzno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="idst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="phrno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nmprnst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cncdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsidst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="scridst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="cncremark" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="otaxno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email_sro" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="email_contract_real" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ID_main" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="person_status_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="person_status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="sex" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="register_capital" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslcnsid_t" Member="syslcnsid_ts">
    <Type Name="syslcnsid_t">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crtlct" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ntcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="taxno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="trdregno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ctzno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="idst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="phrno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nmprnst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cncdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lcnsidst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="scridst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="cncremark" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslcnsnm" Member="syslcnsnms">
    <Type Name="syslcnsnm">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="identify" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnscd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prefixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="prefixcd2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="prefixnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="prefixnm2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="engnm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thalnm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="englnm" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="suffixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lcnsst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="grplcnscd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="bsncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="lcnsidst" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="validdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="oldid" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslctaddr" Member="syslctaddrs">
    <Type Name="syslctaddr">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="identify" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thaaddr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="engaddr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="room" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="mu" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="floor" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="thasoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="building" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="engsoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="tharoad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="engroad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thmblnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amphrnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="chngwtnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="validdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="pvcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ttcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="branch" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Fulladdr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslctaddr_t" Member="syslctaddr_ts">
    <Type Name="syslctaddr_t">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="thaaddr" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="engaddr" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="room" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="mu" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="floor" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="thasoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="building" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="engsoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="tharoad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="engroad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="validdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="pvcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ttcode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="branch" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslctnm" Member="syslctnms">
    <Type Name="syslctnm">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lctnmcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prefixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="engnm" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="suffixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lctst" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="tpnost" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ltntpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hptno" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="lcttpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctnmno" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dvcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="grplctnmcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thanmold" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="prefixcdold" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslctnm_t" Member="syslctnm_ts">
    <Type Name="syslctnm_t">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lctnmcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="prefixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="engnm" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="suffixcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lctst" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="tpnost" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ltntpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hptno" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="lcttpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctnmno" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dvcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="grplctnmcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thanmold" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="prefixcdold" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.syslcttype" Member="syslcttypes">
    <Type Name="syslcttype">
      <Column Name="lcttpcd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="lcttpnm" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="fda.sysnitiperson" Member="sysnitipersons">
    <Type Name="sysnitiperson">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="identify" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="taxno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctnmcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lcnscd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firstname_th" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lastname_th" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="firstname_eng" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lastname_eng" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsst" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_connect_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.sysnmperson" Member="sysnmpersons">
    <Type Name="sysnmperson">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="identify" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="taxno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnscd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="engnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thalnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="englnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bsncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prefixcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="suffixcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_connect_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="update_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="fda.systelfax" Member="systelfaxes">
    <Type Name="systelfax">
      <Column Name="lcnsid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="dvcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sysemail" Member="sysemails">
    <Type Name="sysemail">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL_EGA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EMAIL_FDA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MOBILE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TEL_WORK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WORK_HOLIDAY" Member="WORK_HOLIDAYs">
    <Type Name="WORK_HOLIDAY">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="holdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="holdtpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TITLE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FULL_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TOKEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>